### ISSUE TITLE
NPE whenever I use a non-default reporter

### ISSUE THREAD

**Issue by ztellman** [weavejester/eftest#6]
If I uncomment the option map at https://github.com/lacuna/bifurcan/blob/master/test/bifurcan/run_tests.clj#L12, I'll get the following error.  Having looked over the code, I don't see any obvious reason for this to be the case, though maybe it's some sort of loading race condition?

```
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at clojure.lang.Namespace.find(Namespace.java:188)
	at clojure.core$find_ns.invokeStatic(core.clj:4000)
	at clojure.core$the_ns.invokeStatic(core.clj:4030)
	at clojure.core$the_ns.invoke(core.clj:4023)
	at eftest.runner$test_ns.invokeStatic(runner.clj:31)
	at eftest.runner$test_ns.invoke(runner.clj:30)
	at eftest.runner$test_all$fn__5800.invoke(runner.clj:40)
	at clojure.core$map$fn__4785.invoke(core.clj:2646)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1749)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at eftest.runner$test_all.invokeStatic(runner.clj:41)
	at eftest.runner$test_all.invoke(runner.clj:38)
	at eftest.runner$run_tests.invokeStatic(runner.clj:93)
	at eftest.runner$run_tests.invoke(runner.clj:76)
	at bifurcan.run_tests$_main.invokeStatic(run_tests.clj:9)
	at bifurcan.run_tests$_main.doInvoke(run_tests.clj:5)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5846.invokeStatic(form-init8518620352353107416.clj:1)
	at user$eval5846.invoke(form-init8518620352353107416.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
```

**Comment by weavejester** [comment]
I suspect it's just that you're putting the options map as the first argument rather than the second, since you're using `->>` and not `->`.

**Comment by ztellman** [comment]
Sigh, yes, that was it.  Thank you for the quick reply, and sorry for making you debug my code for me.

**Comment by ztellman** [comment]
Also, thank you for the library. This is the first time in recent memory my development has been test-bounded, and the parallel execution has made a huge difference.

**Comment by weavejester** [comment]
You're very welcome.

Maybe once clojure.spec comes into common usage, errors like this will be easier to debug. I've been hit by bugs like this a lot, since maps implement `IFn` and that obfuscates the exception.
